/*Select * From INFORMATION_SCHEMA.TABLES

Select * From INFORMATION_SCHEMA.COLUMNS
WHERE table_name = 'dim_customers'     */

--Explore all countries where customers come from
Select DISTINCT country
From gold.dim_customers
-- explore all categories "the major divisions"
Select DISTINCT category, subcategory, product_name
From gold.dim_products
Order By 1,2,3

--Identify the earliest and latest dates (boundaries).
--Understand the scope of data and the timespan.
Select MIN(order_date) as first_order_date,
MAX(order_date) as last_order_date,
DATEDIFF(year,MIN(order_date),MAX(order_date)) order_range_years
 from gold.fact_sales


--Find the youngest and the oldest customer
SELECT
MIN(birthdate) AS oldest_birthdate,
DATEDIFF(year, MIN(birthdate), GETDATE()) as oldest_age,
MAX(birthdate) AS youngest_birthdate,
DATEDIFF(year, MAX(birthdate), GETDATE()) as youngest_age
FROM gold.dim_customers

--measures exploration

--Find the Total Sales
SELECT sum(sales_amount) AS total_sales from gold.fact_sales

--Find how many items are sold
SELECT sum(quantity) AS total_quantity FROM gold.fact_sales

--Find the average selling price
SELECT avg(price) AS avg_price from gold.fact_sales

--Find the Total number of Orders
SELECT count(order_number) AS total_orders from gold.fact_sales
SELECT count(DISTINCT order_number) AS total_orders from gold.fact_sales

--Find the total number of products
SELECT count(product_key) AS total_products from gold.fact_sales
 
--Find the total number of customers
SELECT count(customer_key) AS total_customers from gold.dim_customers

--Find the total number of customers that has placed an order
SELECT count(DISTINCT customer_key) AS total_customers from gold.fact_sales


-- Generate a Report that shows all key metrics of the business

SELECT 'Total Sales' AS measure_name, SUM(sales_amount) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Quantity', SUM(quantity) FROM gold.fact_sales
UNION ALL
SELECT 'Average Price', AVG(price) FROM gold.fact_sales
UNION ALL
SELECT 'Total Nr. Orders', COUNT(DISTINCT order_number) FROM gold.fact_sales
UNION ALL
SELECT 'Total Nr. Products', COUNT(product_name) FROM gold.dim_products
UNION ALL
SELECT 'Total Nr. Customers', COUNT(customer_key) FROM gold.dim_customers

--Find total customers by countries
SELECT country, count(customer_key) AS total_customers from gold.dim_customers
Group by country
Order by total_customers DESC

--Find total customers by gender
SELECT gender, count(customer_key) AS total_customers from gold.dim_customers
Group by gender
Order by total_customers DESC

--Find total products by category
SELECT category, count(product_key) AS total_products from gold.dim_products
Group by category
Order by total_products DESC

--What is the average costs in each category?
SELECT category, avg(cost) AS avg_cost from gold.dim_products
Group by category
Order by avg_cost DESC
--What is the total revenue generated for each category?
select pd.category, SUM(sa.sales_amount) sales_by_category
from gold.fact_sales sa
Left Join gold.dim_products pd
ON sa.product_key = pd.product_key
Group by category
Order By sales_by_category DESC

--Find total revenue generated by each customer
SELECT
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) as total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
group by c.customer_key,c.first_name, c.last_name
Order by total_revenue DESC

--What is the distribution of sold items across countries?
SELECT
cu.country,
SUM(fs.sales_amount) total_sales, SUM(fs.quantity) total_quantity
from gold.fact_sales fs
LEFT JOIN gold.dim_customers cu 
ON fs.customer_key = cu.customer_key
Group by cu.country Order by total_quantity DESC


--Ranking analysis
-- Which 5 products generate the highest revenue?
SELECT TOP 5
p.product_name,
SUM(f.sales_amount) total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f. product_key
GROUP BY p.product_name
ORDER BY total_revenue DESC

--window fxn below
Select* from(
SELECT
p.product_name,
SUM(f.sales_amount) total_revenue,
RANK() OVER(Order By SUM(f.sales_amount) DESC ) Ranking
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f. product_key
Group by p.product_name 
)t Where Ranking<=5

-- What are the 5 worst-performing products in terms of sales?
SELECT TOP 5
p.product_name,
SUM(f.sales_amount) total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f. product_key
GROUP BY p.product_name
ORDER BY total_revenue ASC

-- The 3 customers with the fewest orders placed

SELECT TOP 3
c.customer_key,
c.first_name,
c.last_name,
COUNT(DISTINCT order_number) AS total_orders
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY
c.customer_key,
c.first_name,
c.last_name
ORDER BY total_orders
